package pojo;
// Generated Aug 24, 2019 4:40:57 PM by Hibernate Tools 4.3.1



/**
 * Diem generated by hbm2java
 */
public class Diem  implements java.io.Serializable {


     private int id;
     private String maSinhVien;
     private String maLopTkb;
     private String hoTen;
     private Float diemGk;
     private Float diemCk;
     private Float deimKhac;
     private Float diemTong;

    public Diem() {
    }

	
    public Diem(int id, String maSinhVien, String maLopTkb) {
        this.id = id;
        this.maSinhVien = maSinhVien;
        this.maLopTkb = maLopTkb;
    }
    public Diem(int id, String maSinhVien, String maLopTkb, String hoTen, Float diemGk, Float diemCk, Float deimKhac, Float diemTong) {
       this.id = id;
       this.maSinhVien = maSinhVien;
       this.maLopTkb = maLopTkb;
       this.hoTen = hoTen;
       this.diemGk = diemGk;
       this.diemCk = diemCk;
       this.deimKhac = deimKhac;
       this.diemTong = diemTong;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMaSinhVien() {
        return this.maSinhVien;
    }
    
    public void setMaSinhVien(String maSinhVien) {
        this.maSinhVien = maSinhVien;
    }
    public String getMaLopTkb() {
        return this.maLopTkb;
    }
    
    public void setMaLopTkb(String maLopTkb) {
        this.maLopTkb = maLopTkb;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public Float getDiemGk() {
        return this.diemGk;
    }
    
    public void setDiemGk(Float diemGk) {
        this.diemGk = diemGk;
    }
    public Float getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(Float diemCk) {
        this.diemCk = diemCk;
    }
    public Float getDeimKhac() {
        return this.deimKhac;
    }
    
    public void setDeimKhac(Float deimKhac) {
        this.deimKhac = deimKhac;
    }
    public Float getDiemTong() {
        return this.diemTong;
    }
    
    public void setDiemTong(Float diemTong) {
        this.diemTong = diemTong;
    }




}


