package pojo;
// Generated Aug 24, 2019 4:40:57 PM by Hibernate Tools 4.3.1



/**
 * NguoiDung generated by hbm2java
 */
public class NguoiDung  implements java.io.Serializable {


     private int id;
     private String hoTen;
     private String maNguoiDung;
     private String gioiTinh;
     private String cmnd;
     private int role;
     private Integer dangNhapLanDau;
     private String maLop;
     private String moTa;
     private String matKhau;

    public NguoiDung() {
    }

	
    public NguoiDung(int id, String hoTen, int role, String maLop, String matKhau) {
        this.id = id;
        this.hoTen = hoTen;
        this.role = role;
        this.maLop = maLop;
        this.matKhau = matKhau;
    }
    public NguoiDung(int id, String hoTen, String maNguoiDung, String gioiTinh, String cmnd, int role, Integer dangNhapLanDau, String maLop, String moTa, String matKhau) {
       this.id = id;
       this.hoTen = hoTen;
       this.maNguoiDung = maNguoiDung;
       this.gioiTinh = gioiTinh;
       this.cmnd = cmnd;
       this.role = role;
       this.dangNhapLanDau = dangNhapLanDau;
       this.maLop = maLop;
       this.moTa = moTa;
       this.matKhau = matKhau;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getMaNguoiDung() {
        return this.maNguoiDung;
    }
    
    public void setMaNguoiDung(String maNguoiDung) {
        this.maNguoiDung = maNguoiDung;
    }
    public String getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public int getRole() {
        return this.role;
    }
    
    public void setRole(int role) {
        this.role = role;
    }
    public Integer getDangNhapLanDau() {
        return this.dangNhapLanDau;
    }
    
    public void setDangNhapLanDau(Integer dangNhapLanDau) {
        this.dangNhapLanDau = dangNhapLanDau;
    }
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }




}


