package pojo;
// Generated Aug 24, 2019 4:40:57 PM by Hibernate Tools 4.3.1



/**
 * SinhVienTkb generated by hbm2java
 */
public class SinhVienTkb  implements java.io.Serializable {


     private int id;
     private String maSinhVien;
     private String maLopTkb;
     private String maMonHoc;

    public SinhVienTkb() {
    }

	
    public SinhVienTkb(int id, String maSinhVien, String maLopTkb) {
        this.id = id;
        this.maSinhVien = maSinhVien;
        this.maLopTkb = maLopTkb;
    }
    public SinhVienTkb(int id, String maSinhVien, String maLopTkb, String maMonHoc) {
       this.id = id;
       this.maSinhVien = maSinhVien;
       this.maLopTkb = maLopTkb;
       this.maMonHoc = maMonHoc;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMaSinhVien() {
        return this.maSinhVien;
    }
    
    public void setMaSinhVien(String maSinhVien) {
        this.maSinhVien = maSinhVien;
    }
    public String getMaLopTkb() {
        return this.maLopTkb;
    }
    
    public void setMaLopTkb(String maLopTkb) {
        this.maLopTkb = maLopTkb;
    }
    public String getMaMonHoc() {
        return this.maMonHoc;
    }
    
    public void setMaMonHoc(String maMonHoc) {
        this.maMonHoc = maMonHoc;
    }




}


