package pojo;
// Generated Aug 24, 2019 4:40:57 PM by Hibernate Tools 4.3.1



/**
 * ThoiKhoaBieu generated by hbm2java
 */
public class ThoiKhoaBieu  implements java.io.Serializable {


     private int id;
     private String maMon;
     private String tenMonHoc;
     private String phongHoc;
     private String maLop;

    public ThoiKhoaBieu() {
    }

	
    public ThoiKhoaBieu(int id, String maMon, String phongHoc, String maLop) {
        this.id = id;
        this.maMon = maMon;
        this.phongHoc = phongHoc;
        this.maLop = maLop;
    }
    public ThoiKhoaBieu(int id, String maMon, String tenMonHoc, String phongHoc, String maLop) {
       this.id = id;
       this.maMon = maMon;
       this.tenMonHoc = tenMonHoc;
       this.phongHoc = phongHoc;
       this.maLop = maLop;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMaMon() {
        return this.maMon;
    }
    
    public void setMaMon(String maMon) {
        this.maMon = maMon;
    }
    public String getTenMonHoc() {
        return this.tenMonHoc;
    }
    
    public void setTenMonHoc(String tenMonHoc) {
        this.tenMonHoc = tenMonHoc;
    }
    public String getPhongHoc() {
        return this.phongHoc;
    }
    
    public void setPhongHoc(String phongHoc) {
        this.phongHoc = phongHoc;
    }
    public String getMaLop() {
        return this.maLop;
    }
    
    public void setMaLop(String maLop) {
        this.maLop = maLop;
    }




}


