package pojo;
// Generated Aug 24, 2019 4:40:57 PM by Hibernate Tools 4.3.1



/**
 * YeuCauPhucKhao generated by hbm2java
 */
public class YeuCauPhucKhao  implements java.io.Serializable {


     private int id;
     private String maSinhVien;
     private String maMonHoc;
     private String hoTen;
     private String cotDiemPk;
     private Integer diemMongMuon;
     private String lyDo;
     private String tinhTrang;

    public YeuCauPhucKhao() {
    }

	
    public YeuCauPhucKhao(int id, String maSinhVien, String maMonHoc, String cotDiemPk, String tinhTrang) {
        this.id = id;
        this.maSinhVien = maSinhVien;
        this.maMonHoc = maMonHoc;
        this.cotDiemPk = cotDiemPk;
        this.tinhTrang = tinhTrang;
    }
    public YeuCauPhucKhao(int id, String maSinhVien, String maMonHoc, String hoTen, String cotDiemPk, Integer diemMongMuon, String lyDo, String tinhTrang) {
       this.id = id;
       this.maSinhVien = maSinhVien;
       this.maMonHoc = maMonHoc;
       this.hoTen = hoTen;
       this.cotDiemPk = cotDiemPk;
       this.diemMongMuon = diemMongMuon;
       this.lyDo = lyDo;
       this.tinhTrang = tinhTrang;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMaSinhVien() {
        return this.maSinhVien;
    }
    
    public void setMaSinhVien(String maSinhVien) {
        this.maSinhVien = maSinhVien;
    }
    public String getMaMonHoc() {
        return this.maMonHoc;
    }
    
    public void setMaMonHoc(String maMonHoc) {
        this.maMonHoc = maMonHoc;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getCotDiemPk() {
        return this.cotDiemPk;
    }
    
    public void setCotDiemPk(String cotDiemPk) {
        this.cotDiemPk = cotDiemPk;
    }
    public Integer getDiemMongMuon() {
        return this.diemMongMuon;
    }
    
    public void setDiemMongMuon(Integer diemMongMuon) {
        this.diemMongMuon = diemMongMuon;
    }
    public String getLyDo() {
        return this.lyDo;
    }
    
    public void setLyDo(String lyDo) {
        this.lyDo = lyDo;
    }
    public String getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(String tinhTrang) {
        this.tinhTrang = tinhTrang;
    }




}


